IRPTeam/IRP

IRP/src/Catalogs/Agreements/Agreements.mdo
Сделал фильтр на все предопределенные, так как отдельно только на ручной тип цен - надо писать механизм. Когда такая задача будет, тогда и вернемся сюда
=> Update Agreements.mdo resolve #38

IRP/src/CommonModules/DocBundlingClient/Module.bsl, IRP/src/CommonModules/DocUnbundlingClient/Module.bsl, IRP/src/Documents/Bundling/Forms/DocumentForm/Form.form, IRP/src/Documents/Bundling/Forms/DocumentForm/Module.bsl, IRP/src/Documents/Unbundling/Forms/DocumentForm/Form.form, IRP/src/Documents/Unbundling/Forms/DocumentForm/Module.bsl
=> #12 add button

IRP/src/CommonForms/PictureGalleryForm/Module.bsl, IRP/src/CommonModules/PictureViewerClient/Module.bsl, IRP/src/CommonModules/PictureViewerServer/Module.bsl
=> Issue 51 error when adding a picture from gallery to item

IRP/src/CommonModules/DocBundlingClient/Module.bsl, IRP/src/CommonModules/DocGoodsReceiptClient/Module.bsl, IRP/src/CommonModules/DocInternalSupplyRequestClient/Module.bsl, IRP/src/CommonModules/DocInventoryTransferClient/Module.bsl, IRP/src/CommonModules/DocInventoryTransferOrderClient/Module.bsl, IRP/src/CommonModules/DocPhysicalCountByLocationClient/Module.bsl, IRP/src/CommonModules/DocPhysicalInventoryClient/Module.bsl, IRP/src/CommonModules/DocPurchaseInvoiceClient/Module.bsl, IRP/src/CommonModules/DocPurchaseOrderClient/Module.bsl, IRP/src/CommonModules/DocPurchaseReturnClient/Module.bsl, IRP/src/CommonModules/DocPurchaseReturnOrderClient/Module.bsl, IRP/src/CommonModules/DocSalesInvoiceClient/Module.bsl, IRP/src/CommonModules/DocSalesOrderClient/Module.bsl, IRP/src/CommonModules/DocSalesReturnClient/Module.bsl, IRP/src/CommonModules/DocSalesReturnOrderClient/Module.bsl, IRP/src/CommonModules/DocShipmentConfirmationClient/Module.bsl, IRP/src/CommonModules/DocStockAdjustmentAsSurplusClient/Module.bsl, IRP/src/CommonModules/DocStockAdjustmentAsWriteOffClient/Module.bsl, IRP/src/CommonModules/DocUnbundlingClient/Module.bsl
=> fix barcode

IRP/src/Catalogs/Agreements/ManagerModule.bsl, IRP/src/Catalogs/Companies/ManagerModule.bsl, IRP/src/Catalogs/ObjectStatuses/ManagerModule.bsl, IRP/src/Catalogs/Partners/ManagerModule.bsl, IRP/src/Catalogs/Specifications/ManagerModule.bsl, IRP/src/Catalogs/Units/ManagerModule.bsl, IRP/src/CommonModules/CommonFormActionsServer/Module.bsl, IRP/src/CommonModules/LocalizationEvents/Module.bsl, IRP/src/Configuration/Configuration.mdo
#58 новый вид получения данных по строке
=> обновил механизм ввода по строке

IRP/src/Catalogs/ItemKeys/Forms/ItemForm/Form.form, IRP/src/Catalogs/Items/Forms/ItemForm/Form.form
=> fix pic view

IRP/src/Catalogs/Files/Forms/ItemForm/Module.bsl, IRP/src/Catalogs/IntegrationSettings/Forms/ItemForm/Module.bsl, IRP/src/CommonForms/HTMLField/Form.form, IRP/src/CommonForms/HTMLField/Module.bsl, IRP/src/CommonModules/GoogleDriveClient/Module.bsl, IRP/src/CommonModules/GoogleDriveClientServer/GoogleDriveClientServer.mdo, IRP/src/CommonModules/GoogleDriveClientServer/Module.bsl, IRP/src/CommonModules/GoogleDriveServer/GoogleDriveServer.mdo, IRP/src/CommonModules/GoogleDriveServer/Module.bsl, IRP/src/CommonModules/IntegrationServer/Module.bsl, IRP/src/CommonModules/IntegrationServerReuse/Module.bsl, IRP/src/CommonModules/PictureViewerClient/Module.bsl, IRP/src/CommonModules/PictureViewerClientServer/Module.bsl, IRP/src/CommonModules/PictureViewerServer/Module.bsl, IRP/src/Configuration/Configuration.mdo, IRP/src/Subsystems/Settings/Subsystems/Integrations/Subsystems/GoogleDrive/GoogleDrive.mdo
=> #131 #69 #292

IRP/src/Catalogs/CashAccounts/CashAccounts.mdo, IRP/src/Catalogs/CashAccounts/Forms/ItemForm/Form.form, IRP/src/Catalogs/CashAccounts/Forms/ItemForm/Module.bsl, IRP/src/CommonModules/CalculationStringsClientServer/Module.bsl, IRP/src/CommonModules/DocBankReceiptClient/Module.bsl, IRP/src/CommonModules/DocBankReceiptServer/Module.bsl, IRP/src/CommonModules/DocCashStatementServer/Module.bsl, IRP/src/CommonModules/DocumentsServer/Module.bsl, IRP/src/DefinedTypes/typePlaningTransactionBasises/typePlaningTransactionBasises.mdo, IRP/src/Documents/BankPayment/BankPayment.mdo, IRP/src/Documents/BankPayment/Forms/DocumentForm/Form.form, IRP/src/Documents/BankPayment/ManagerModule.bsl, IRP/src/Documents/BankReceipt/BankReceipt.mdo, IRP/src/Documents/BankReceipt/Forms/DocumentForm/ConditionalAppearance.dcssca, IRP/src/Documents/BankReceipt/Forms/DocumentForm/Form.form, IRP/src/Documents/BankReceipt/Forms/DocumentForm/Module.bsl, IRP/src/Documents/BankReceipt/ManagerModule.bsl, IRP/src/Documents/BankReceipt/ObjectModule.bsl, IRP/src/Documents/CashRevenue/Forms/DocumentForm/Form.form, IRP/src/Documents/CashStatement/CashStatement.mdo, IRP/src/Documents/CashStatement/Forms/DocumentForm/Form.form, IRP/src/Documents/CashStatement/Forms/DocumentForm/Module.bsl, IRP/src/Documents/CashStatement/ManagerModule.bsl, IRP/src/Enums/IncomingPaymentTransactionType/IncomingPaymentTransactionType.mdo
=> Issue 282 add movement for retail docs with new registers

IRP/src/CommonModules/DocSalesInvoiceClient/Module.bsl, IRP/src/CommonModules/DocumentsClient/Module.bsl, IRP/src/Documents/PurchaseInvoice/Forms/DocumentForm/Module.bsl
=> #451 purchase invoice

IRP/src/CommonForms/EditUserSettings/Form.form, IRP/src/CommonForms/EditUserSettings/Module.bsl
=> #1 Added collapse and expand buttons to user settings form

IRP/src/Reports/DocumentRegistrationsReport/Forms/ReportForm/Attributes/ResultTable/ExtInfo/SpreadsheetData.mxlx, IRP/src/Reports/DocumentRegistrationsReport/Forms/ReportForm/Form.form, IRP/src/Reports/DocumentRegistrationsReport/Forms/ReportForm/Module.bsl
#1 Improved document registration report
=> #1 Improved document registration report

IRP/src/DataProcessors/PrintLabels/ObjectModule.bsl, IRP/src/Roles/BasicRole/Rights.rights
=> Issue print fixes

IRP/src/CommonModules/DocSalesInvoiceClient/Module.bsl, IRP/src/CommonModules/DocumentsClient/Module.bsl, IRP/src/Documents/SalesInvoice/Commands/GenerateSalesInvoice/CommandModule.bsl
=> #1 bugfix aging

IRP/src/Documents/InventoryTransferOrder/ManagerModule.bsl, IRP/src/Documents/ItemStockAdjustment/Forms/ChoiceForm/Form.form, IRP/src/Documents/ItemStockAdjustment/Forms/ListForm/Form.form, IRP/src/Documents/ItemStockAdjustment/ManagerModule.bsl, IRP/src/Documents/PurchaseInvoice/ManagerModule.bsl
=> #767 bugfix

IRP/src/AccumulationRegisters/R1031B_ReceiptInvoicing/R1031B_ReceiptInvoicing.mdo, IRP/src/AccumulationRegisters/R2031B_ShipmentInvoicing/R2031B_ShipmentInvoicing.mdo, IRP/src/Documents/GoodsReceipt/ManagerModule.bsl, IRP/src/Documents/PurchaseInvoice/Commands/GeneratePurchaseInvoice/CommandModule.bsl, IRP/src/Documents/PurchaseInvoice/ManagerModule.bsl, IRP/src/Documents/SalesInvoice/ManagerModule.bsl, IRP/src/Documents/ShipmentConfirmation/ManagerModule.bsl, features/Internal/_0170 Purchase/_0224GR_PI.feature
#766 filling Store on generate PI
=> #766 filling Store on generate PI

IRP/src/Documents/BankPayment/ManagerModule.bsl, IRP/src/Documents/BankReceipt/ManagerModule.bsl, IRP/src/Documents/CashPayment/ManagerModule.bsl, IRP/src/Documents/CashReceipt/ManagerModule.bsl
=>  #1189 R3010B_CashOnHand of CP/CR/BP/BR

IRP/src/CommonModules/CurrenciesClient/Module.bsl
Лучше не использовать практику: вставлять функции в объявлении цикла.
=> Refact module

IRP/src/CommonModules/ViewClient_V2/Module.bsl, IRP/src/CommonModules/ViewServer_V2/Module.bsl, IRP/src/Documents/PriceList/Forms/DocumentForm/Form.form, IRP/src/Documents/PriceList/Forms/DocumentForm/Module.bsl, features/Internal/_0160 Price/_0160PriceByItemkey.feature, features/Internal/_0170 Purchase/_0170PCreatePurchaseOrder.feature, features/Internal/_0170 Purchase/_0180CreatePurchaseInvoice.feature, features/Internal/_0288 Inventory/_0288PostingShipmentConfirmation.feature, features/Internal/_9500AccessRights/_9504LockDataModification.feature
=> issue1259_1244

IRP/src/AccumulationRegisters/R3050T_PosCashBalances/ManagerModule.bsl, IRP/src/AccumulationRegisters/R3050T_PosCashBalances/R3050T_PosCashBalances.mdo, IRP/src/CommonModules/DocCashStatementServer/Module.bsl, IRP/src/Configuration/Configuration.mdo, IRP/src/Documents/RetailReturnReceipt/ManagerModule.bsl, IRP/src/Documents/RetailReturnReceipt/RetailReturnReceipt.mdo, IRP/src/Documents/RetailSalesReceipt/ManagerModule.bsl, IRP/src/Documents/RetailSalesReceipt/RetailSalesReceipt.mdo, IRP/src/ExchangePlans/FullExchange/FullExchange.mdo, IRP/src/FunctionalOptions/UseBusinessUnits/UseBusinessUnits.mdo, IRP/src/FunctionalOptions/UseRetail/UseRetail.mdo, IRP/src/Roles/FullAccessInArea/Rights.rights, IRP/src/Roles/FullAccessOnlyRead/Rights.rights, IRP/src/Subsystems/Retail/Retail.mdo, features/Internal/_0287 Services/_0287Services.feature
=> #1327 Rename Accum register R3050T_RetailCash to R3050T_PosCashBalances

IRP/src/Documents/StockAdjustmentAsSurplus/Forms/DocumentForm/Form.form, IRP/src/Documents/StockAdjustmentAsSurplus/ManagerModule.bsl, IRP/src/Documents/StockAdjustmentAsSurplus/StockAdjustmentAsSurplus.mdo
=> issue 1437

IRP/src/Catalogs/Partners/Forms/ChoiceForm/Module.bsl, IRP/src/Catalogs/Partners/Forms/ItemForm/Form.form, IRP/src/Catalogs/Partners/Forms/ItemForm/Module.bsl, IRP/src/Catalogs/Partners/Forms/ListForm/Module.bsl, IRP/src/InformationRegisters/RetailWorkers/Commands/RetailWorkers/CommandModule.bsl, IRP/src/InformationRegisters/RetailWorkers/RetailWorkers.mdo, IRP/src/Roles/FullAccessOnlyRead/Rights.rights
=> issue 1407

IRP/src/CommonModules/ControllerClientServer_V2/Module.bsl
=> Fix Bulder API by recalculate Total Amount #1508

IRP/src/Catalogs/ItemKeys/ManagerModule.bsl, IRP/src/CommonAttributes/Author/Author.mdo, features/Internal/_0910 Forms/_1540Forms.feature, features/Internal/_0912 Filling documents/_2021Fillingdocument.feature
=> Issue_1512

IRP/src/CommonModules/ControllerClientServer_V2/Module.bsl, IRP/src/CommonModules/ModelClientServer_V2/Module.bsl
=> web_client_bug_fix

IRP/src/Catalogs/ObjectStatuses/Forms/ItemForm/Form.form, IRP/src/Catalogs/ObjectStatuses/Forms/ItemForm/Module.bsl, IRP/src/CommonModules/ObjectStatusesClient/Module.bsl, features/Internal/_0050 Catalogs/_00503ObjectStatusesCatalog.feature
Удален устаревший код из выбора статуса объекта.
=> #1377 Deleted old code

IRP/src/CommonModules/ControllerClientServer_V2/Module.bsl, IRP/src/CommonModules/DocGoodsReceiptClient/Module.bsl, IRP/src/CommonModules/DocShipmentConfirmationClient/Module.bsl, IRP/src/CommonModules/ModelClientServer_V2/Module.bsl, IRP/src/CommonModules/ViewClient_V2/Module.bsl, IRP/src/Documents/GoodsReceipt/Forms/DocumentForm/Module.bsl, IRP/src/Documents/ShipmentConfirmation/Forms/DocumentForm/Module.bsl
=>  GR - when changing TransactionType not clearing Partner and LegalName #1460 

IRP/src/AccumulationRegisters/R2001T_Sales/R2001T_Sales.mdo
=> #1585 Add type

IRP/src/CommonModules/ControllerClientServer_V2/Module.bsl, IRP/src/CommonModules/RowIDInfoServer/Module.bsl, features/Internal/_5000CommissionTrade/_5802ComissionTradeOwnCompanies.feature
=> issue_1598

IRP/src/CommonModules/RowIDInfoServer/Module.bsl
=> retail orders (prepaid to advance)

IRP/src/CommonModules/SerialLotNumberClient/Module.bsl, IRP/src/CommonModules/SerialLotNumbersServer/Module.bsl, features/Internal/_0920 SerialLotNumbers/_0920SerialLotNumber.feature
=> issue_1621

IRP/src/CommonModules/FOServer/Module.bsl, IRP/src/Configuration/Configuration.mdo, IRP/src/Constants/UseRetailOrders/UseRetailOrders.mdo, IRP/src/Enums/SalesTransactionTypes/ManagerModule.bsl, IRP/src/FunctionalOptions/UseRetailOrders/UseRetailOrders.mdo, IRP/src/Roles/FullAccessOnlyRead/Rights.rights, features/External/Podgotovka.feature, features/Internal/_0250RetailDocuments/_2024FillingRetailDocuments.feature, features/Internal/_9000FunctionalOptions/_9001UseSimpleMode.feature, features/Internal/_9000FunctionalOptions/_9010UseTransactionTypesFO.feature
=> functional options (retail orders)

IRP/src/Documents/RetailSalesReceipt/ManagerModule.bsl, features/Internal/_0400 Movements/_424RetailSalesReceiptMovements.feature
=> issue 1664

IRP/src/CommonModules/DocBankPaymentClient/Module.bsl, IRP/src/CommonModules/DocBankReceiptClient/Module.bsl
=> issue 1684

IRP/src/CommonModules/PostingServer/Module.bsl, IRP/src/Documents/Bundling/ObjectModule.bsl, IRP/src/Documents/GoodsReceipt/ObjectModule.bsl, IRP/src/Documents/InventoryTransfer/ObjectModule.bsl, IRP/src/Documents/InventoryTransferOrder/ObjectModule.bsl, IRP/src/Documents/ItemStockAdjustment/ObjectModule.bsl, IRP/src/Documents/OpeningEntry/ObjectModule.bsl, IRP/src/Documents/PhysicalInventory/ObjectModule.bsl, IRP/src/Documents/Production/ObjectModule.bsl, IRP/src/Documents/PurchaseInvoice/ObjectModule.bsl, IRP/src/Documents/PurchaseReturn/ObjectModule.bsl, IRP/src/Documents/RetailReturnReceipt/ObjectModule.bsl, IRP/src/Documents/RetailSalesReceipt/ObjectModule.bsl, IRP/src/Documents/SalesInvoice/ObjectModule.bsl, IRP/src/Documents/SalesOrder/ObjectModule.bsl, IRP/src/Documents/SalesOrderClosing/ObjectModule.bsl, IRP/src/Documents/SalesReportFromTradeAgent/ObjectModule.bsl, IRP/src/Documents/SalesReturn/ObjectModule.bsl, IRP/src/Documents/ShipmentConfirmation/ObjectModule.bsl, IRP/src/Documents/StockAdjustmentAsSurplus/ObjectModule.bsl, IRP/src/Documents/StockAdjustmentAsWriteOff/ObjectModule.bsl, IRP/src/Documents/Unbundling/ObjectModule.bsl, IRP/src/Documents/WorkOrder/ObjectModule.bsl, IRP/src/Documents/WorkSheet/ObjectModule.bsl
=> check balance optimization

IRP/src/CommonModules/GetItemInfo/Module.bsl, IRP/src/DefinedTypes/typeBarcode/typeBarcode.mdo, IRP/src/InformationRegisters/Barcodes/Barcodes.mdo, Unit/src/CommonModules/Unit_CommonTests/Module.bsl
Getting item package dimensions and increased barcode length
=> Getting item package dimensions

IRP/src/CommonModules/RowIDInfoPrivileged/Module.bsl, IRP/src/CommonModules/RowIDInfoServer/Module.bsl, IRP/src/FunctionalOptions/UseManufacturing/UseManufacturing.mdo
=> refactoring row id

IRP/src/Catalogs/Hardware/Forms/ItemForm/Form.form, IRP/src/CommonModules/EquipmentFiscalPrinterClient/Module.bsl, IRP/src/CommonModules/EquipmentFiscalPrinterServer/Module.bsl, IRP/src/DataProcessors/PointOfSale/Forms/Form/Module.bsl, features/Internal/_8510FiscalPrinter/_8510FiscalPrinter.feature
=> Add print slip transaction from terminal #1760

IRP/src/CommonModules/RowIDInfoServer/Module.bsl, features/External/ImportDocumentsCreationBaseOn.feature, features/Internal/_0950 LinkedTransaction/_2067LockingLinkedStringsInventoryTransfersOneSession.feature
=> rowid bugfix

IRP/src/CommonModules/CurrenciesClientServer/Module.bsl, IRP/src/CommonModules/RowIDInfoServer/Module.bsl
=> rowid bugfix optimization

IRP/src/CommonModules/ControllerClientServer_V2/Module.bsl, IRP/src/CommonModules/DocInventoryTransferClient/Module.bsl, IRP/src/Documents/InventoryTransfer/Forms/DocumentForm/Form.form, IRP/src/Documents/InventoryTransfer/Forms/DocumentForm/Module.bsl, IRP/src/Documents/RetailReturnReceipt/ManagerModule.bsl, IRP/src/Documents/RetailSalesReceipt/ManagerModule.bsl, IRP/src/Documents/SalesInvoice/ManagerModule.bsl, IRP/src/Documents/SalesReturn/ManagerModule.bsl
=> consignor inventory bugfix

IRP/src/DataProcessors/ProductionWorkspace/Forms/Form/Module.bsl, features/Internal/_1050 Manufactoring/_5001ProductionWorkSpace.feature
=>  PlanningRefreshRequestProcessingAtServer - ProductionWorkspace #1796 

IRP/src/CommonModules/RowIDInfoServer/Module.bsl
=> rowid bugfix 

IRP/src/Catalogs/SourceOfOrigins/SourceOfOrigins.mdo
=>  StrLen SourceOfOrigin attributes #1825 

IRP/src/AccumulationRegisters/R6010B_BatchWiseBalance/R6010B_BatchWiseBalance.mdo, IRP/src/AccumulationRegisters/R6020B_BatchBalance/ManagerModule.bsl, IRP/src/AccumulationRegisters/R6020B_BatchBalance/R6020B_BatchBalance.mdo, IRP/src/AccumulationRegisters/R6050T_SalesBatches/R6050T_SalesBatches.mdo, IRP/src/AccumulationRegisters/R6060T_CostOfGoodsSold/ManagerModule.bsl, IRP/src/AccumulationRegisters/R6060T_CostOfGoodsSold/R6060T_CostOfGoodsSold.mdo, IRP/src/CommonModules/LandedCostServer/Module.bsl, IRP/src/Reports/BatchBalance/Templates/MainDataCompositionSchema/Template.dcs
=> landedcost bugfix

IRP/src/CommonModules/CommonFormActionsServer/Module.bsl
=>  Party sting intup #1848 

IRP/src/CommonForms/PickupSpecialOffers/Module.bsl, IRP/src/CommonModules/OffersServer/Module.bsl, IRP/src/Configuration/Configuration.mdo, IRP/src/DefinedTypes/typeSpecialOfferBonus/typeSpecialOfferBonus.mdo, IRP/src/Documents/PurchaseInvoice/PurchaseInvoice.mdo, IRP/src/Documents/PurchaseOrder/PurchaseOrder.mdo, IRP/src/Documents/PurchaseReturn/PurchaseReturn.mdo, IRP/src/Documents/PurchaseReturnOrder/PurchaseReturnOrder.mdo, IRP/src/Documents/RetailReturnReceipt/RetailReturnReceipt.mdo, IRP/src/Documents/RetailSalesReceipt/RetailSalesReceipt.mdo, IRP/src/Documents/SalesInvoice/SalesInvoice.mdo, IRP/src/Documents/SalesOrder/SalesOrder.mdo, IRP/src/Documents/SalesReturn/SalesReturn.mdo, IRP/src/Documents/SalesReturnOrder/SalesReturnOrder.mdo
=>  Bonus discount #1904

IRP/src/CommonModules/LocalizationEvents/Module.bsl, features/Internal/_0050 Catalogs/_0120Agreements.feature
=>  Dont find field Table.Ref.Code in Catalog.Agreements #1834 

IRP/src/Catalogs/SerialLotNumbers/Forms/EditListOfSerialLotNumbers/Form.form, IRP/src/Catalogs/SerialLotNumbers/Forms/EditListOfSerialLotNumbers/Module.bsl
#1873 fixed visibility of label about uniqueness
=> #1873 fixed visibility of label about uniqueness

IRP/src/CommonForms/RelatedDocuments/Module.bsl, features/Internal/_0920 SerialLotNumbers/_0920SerialLotNumber.feature, features/Internal/_3000 Other/_3005RelatedDocuments.feature
=> #1861 fixed document order

IRP/src/Catalogs/CashAccounts/ObjectModule.bsl
#1800 Clearing fields of the previous cash account type
=> #1800 Clearing fields of the previous cash account type

IRP/src/Catalogs/PriceTypes/Forms/ItemForm/Module.bsl, IRP/src/Catalogs/PriceTypes/ManagerModule.bsl, IRP/src/Catalogs/PriceTypes/ObjectModule.bsl, features/Internal/_0050 Catalogs/_00512PriceTypesCatalog.feature, features/Internal/_0299 SalesProcurementMethods/_0292CreatePurchaseBaseSalesOrder.feature, features/Internal/_3000 Other/_3005RelatedDocuments.feature
#1577 check exceptions for manual price
=> #1577 check exceptions for manual price

IRP/src/Catalogs/LockDataModificationReasons/Forms/ItemForm/Form.form, IRP/src/Catalogs/LockDataModificationReasons/Forms/ItemForm/Module.bsl, IRP/src/CommonModules/Localization/Module.bsl, features/Internal/_9500 AccessRights/_9504LockDataModification.feature
#1792 type filter in LockDataModificationReasons
=> #1792 type filter in LockDataModificationReasons

IRP/src/CommonForms/ConstantsForm/Form.form, IRP/src/CommonModules/AdditionalDocumentTableControl/Module.bsl, IRP/src/CommonModules/AdditionalDocumentTableControlReuse/Module.bsl, IRP/src/CommonModules/Localization/Module.bsl, IRP/src/Configuration/Configuration.mdo, IRP/src/Constants/UseAdditionalTableControlDocument/UseAdditionalTableControlDocument.mdo, IRP/src/DefinedTypes/AdditionalTableControlDocumentObject/AdditionalTableControlDocumentObject.mdo, IRP/src/EventSubscriptions/BeforeWrite_AdditionalTableControlDocument/BeforeWrite_AdditionalTableControlDocument.mdo
#1919 #1841 Check units before post
=> #1919 #1841 Check units before post

IRP/src/DataProcessors/PointOfSale/Forms/CashOut/Module.bsl, IRP/src/DataProcessors/ProductionWorkspace/Forms/Form/Module.bsl
=>  ProductionWorkspace - InventoryOrigin in InventoryTransfer #1932,  MoneyTranfser when closing shift #1933 

IRP/src/Documents/CashExpense/Forms/DocumentForm/Module.bsl, IRP/src/Documents/CashExpense/ManagerModule.bsl
=> #1928 bugfix

IRP/src/CommonModules/ControllerClientServer_V2/Module.bsl, IRP/src/CommonModules/ModelClientServer_V2/Module.bsl
=>  Cash in transit #1938 

IRP/src/Reports/DocumentRegistrationsReport/Forms/ReportForm/Form.form, IRP/src/Reports/DocumentRegistrationsReport/Forms/ReportForm/Module.bsl
=>  Registration records report #1204 

IRP/src/CommonModules/AdditionalDocumentTableControlReuse/Module.bsl, IRP/src/CommonModules/ViewClient_V2/Module.bsl, IRP/src/DataProcessors/PointOfSale/Forms/Form/Module.bsl
=> Error with RowID and Source of origin #1983

IRP/src/CommonModules/ModelClientServer_V2/Module.bsl
=>  Change price in SI #1984 

IRP/src/Catalogs/BillOfMaterials/ManagerModule.bsl, IRP/src/CommonModules/ControllerClientServer_V2/Module.bsl, IRP/src/CommonModules/ModelClientServer_V2/Module.bsl, IRP/src/CommonModules/ModelServer_V2/Module.bsl
=>  Bill of material filter in the Production documents #2021 

IRP/src/CommonForms/LoadDataFromTable/Form.form, IRP/src/CommonForms/LoadDataFromTable/Module.bsl, IRP/src/CommonModules/LoadDataFromTableClient/Module.bsl, IRP/src/CommonModules/LoadDataFromTableServer/Module.bsl, IRP/src/Documents/PriceList/Forms/DocumentForm/Module.bsl, features/Internal/_2000 LoadInfo/_2010LoadDataForm.feature
=> #1749 - loading document Price List from table

IRP/src/CommonForms/LinkUnlinkDocumentRows/Module.bsl, IRP/src/CommonModules/RowIDInfoClientServer/Module.bsl, IRP/src/CommonModules/RowIDInfoPrivileged/Module.bsl, IRP/src/CommonModules/RowIDInfoServer/Module.bsl, IRP/src/Documents/GoodsReceipt/ManagerModule.bsl, features/Internal/_0950 LinkedTransaction/_2069LockingLinkedStringsRetailSalessOneSession.feature
=> #2054 #2055

IRP/src/CommonModules/RowIDInfoServer/Module.bsl, features/Internal/_0950 LinkedTransaction/_2060LinkUnlinkForm.feature
=>  GR row id linking error #2072 

IRP/src/CommonForms/EditUserSettings/Module.bsl
=>  CommonForm.EditUserSettings Sorting #2074 

IRP/src/AccumulationRegisters/R1011B_PurchaseOrdersReceipt/R1011B_PurchaseOrdersReceipt.mdo, IRP/src/AccumulationRegisters/R2011B_SalesOrdersShipment/R2011B_SalesOrdersShipment.mdo, IRP/src/Documents/RetailShipmentConfirmation/ManagerModule.bsl, features/Internal/_0299 SalesProcurementMethods/_0299SalesOrderNoReserve.feature, features/Internal/_0400 Movements/_0402SalesOrderClosingMovements.feature, features/Internal/_0400 Movements/_0403SalesOrderMovements.feature, features/Internal/_0400 Movements/_0404SalesInvoiceMovements.feature, features/Internal/_0400 Movements/_405ShipmentConfirmationMovements.feature, features/Internal/_0400 Movements/_406PurchaseOrderMovements.feature, features/Internal/_0400 Movements/_407PurchaseInvoiceMovements.feature, features/Internal/_0400 Movements/_408GoodsReceiptMovements.feature, features/Internal/_0400 Movements/_411PurchaseOrderClosingMovements.feature, features/Internal/_0400 Movements/_500RetailShipmentConfirmationMovements.feature
=>  Add RowKey in R1011B_PurchaseOrdersReceipt/R2011B_SalesOrdersShipment #1970 

IRP/src/CommonModules/PostingServer/Module.bsl, features/Internal/_8000 Remaining stock control/_8001RemainingStockControl.feature
=>  NegativeStockControl Error #2083 

IRP/src/Documents/BankPayment/ManagerModule.bsl, IRP/src/Documents/BankReceipt/ManagerModule.bsl, IRP/src/Documents/CashPayment/ManagerModule.bsl, IRP/src/Documents/CashReceipt/ManagerModule.bsl
=>  BP/BR/CR/CP R5015B_OtherPartnersTransactions #2087 

IRP/src/CommonModules/RowIDInfoServer/Module.bsl
=> #2113 Error with settings Calulate rows in the Link form

IRP/src/CommonModules/ViewClient_V2/Module.bsl
=> #2115 Wrong RGR transaction by the register R4032 Goods in transit (outgoing)

IRP/src/Catalogs/Agreements/Agreements.mdo, IRP/src/Catalogs/Agreements/Forms/ItemForm/Form.form, IRP/src/CommonModules/ManufacturingServer/Module.bsl, IRP/src/Documents/Production/ObjectModule.bsl, features/Internal/_1050 Manufactoring/_1000Production.feature, features/Internal/_1050 Manufactoring/_5001ProductionWorkSpace.feature
=> #2188 Branch in Production  #1842 Partner bank account in partner terms

IRP/src/Documents/AdditionalRevenueAllocation/ObjectModule.bsl
=> #2206 Fix AdditionalRevenueAllocation clear record on write

IRP/src/Catalogs/Files/Files.mdo, IRP/src/Catalogs/Files/Forms/ItemForm/Form.form, IRP/src/Catalogs/Files/Forms/ListForm/Attributes/List/ExtInfo/ListSettings.dcss, IRP/src/Catalogs/Files/Forms/ListForm/Form.form, IRP/src/CommonModules/PictureViewerServer/Module.bsl
=> Add Draft attribute to Files

IRP/src/CommonModules/RowIDInfoServer/Module.bsl, features/Internal/_0250 RetailDocuments/_2026RGR_RRR.feature
=> rowid_bugfix

IRP/src/CommonModules/ControllerClientServer_V2/Module.bsl
=> #2196 Add payment in event from builder

IRP/src/Catalogs/Units/ManagerModule.bsl
=> #2167 Filter by units doesn't work when input unit by line

IRP/src/CommonModules/CommissionTradeServer/Module.bsl, features/Internal/_0050 Catalogs/_0049DataBaseStatus.feature
=> #2236 Incorrect user message

IRP/src/CommonModules/DocumentsServer/Module.bsl, IRP/src/CommonModules/SerialLotNumberClientServer/Module.bsl, features/External/ImportData.feature, features/Internal/_5000 CommissionTrade/_5501CommissionProductsSales.feature, features/Internal/_8510 FiscalPrinter/_8510FiscalPrinter.feature
=> #2251 Bug with consignors VAT from SLN

IRP/src/Documents/ConsolidatedRetailSales/Forms/DocumentForm/ConditionalAppearance.dcssca, IRP/src/Documents/ConsolidatedRetailSales/Forms/DocumentForm/Form.form, IRP/src/Documents/ConsolidatedRetailSales/Forms/DocumentForm/Module.bsl, features/Internal/_0260 Retail/_0260Retail.feature, features/Internal/_8510 FiscalPrinter/_8510FiscalPrinter.feature
=> #2048 On double click in CRS

IRP/src/Catalogs/ItemKeys/ObjectModule.bsl, IRP/src/Catalogs/Items/ObjectModule.bsl, IRP/src/CommonModules/GetItemInfo/Module.bsl, IRP/src/CommonModules/Localization/Module.bsl, IRP/src/CommonModules/ServerPrivileged/Module.bsl, IRP/src/CommonModules/ServerPrivileged/ServerPrivileged.mdo, IRP/src/Configuration/Configuration.mdo, features/External/ImportData.feature, features/Internal/_0910 Forms/_2061ItemUnitForm.feature, features/Internal/_3000 Other/_6004ObjectPropertyEditor.feature
=> #2261 Unit in Item 

IRP/src/InformationRegisters/TaxSettings/Forms/RecordForm/Module.bsl, IRP/src/InformationRegisters/TaxSettings/TaxSettings.mdo, IRP/src/Subsystems/Settings/Subsystems/Taxes/CommandInterface.cmi, IRP/src/Subsystems/Settings/Subsystems/Taxes/Taxes.mdo, features/Internal/_9500 AccessRights/_9500FullAccessOnlyRead.feature
=> #2232 #IRP-28 Tax rate settings fix

IRP/src/CommonModules/CatExpenseAndRevenueTypesServer/Module.bsl, IRP/src/CommonModules/ModelClientServer_V2/Module.bsl, IRP/src/InformationRegisters/ExpenseRevenueTypeSettings/ManagerModule.bsl, features/External/Podgotovka1.feature, features/Internal/_0912 Filling documents/_2022FillingExpenceRevenueType.feature
=> #2275 #IRP-67 Autofilling expense types in PI

IRP/src/Catalogs/ItemKeys/Forms/ItemForm/Module.bsl, IRP/src/Catalogs/Items/Forms/ItemForm/Module.bsl, IRP/src/Catalogs/SerialLotNumbers/Forms/ItemForm/Module.bsl, IRP/src/CommonModules/FOServer/Module.bsl, IRP/src/Documents/PurchaseInvoice/Forms/DocumentForm/Module.bsl, IRP/src/Documents/PurchaseInvoice/Forms/ListForm/Module.bsl, IRP/src/Documents/PurchaseReturn/Forms/ListForm/Module.bsl, IRP/src/Documents/SalesInvoice/Forms/ListForm/Module.bsl, IRP/src/Documents/SalesReturn/Forms/ListForm/Module.bsl, IRP/src/Enums/IncomingPaymentTransactionType/ManagerModule.bsl, IRP/src/Enums/OutgoingPaymentTransactionTypes/ManagerModule.bsl, IRP/src/FunctionalOptions/UseChequeBonds/UseChequeBonds.mdo, IRP/src/FunctionalOptions/UseItemKey/UseItemKey.mdo, IRP/src/FunctionalOptions/UseSerialLotNumbers/UseSerialLotNumbers.mdo, IRP/src/FunctionalOptions/UseStores/UseStores.mdo, IRP/src/Subsystems/PurchaseAP/Subsystems/Purchase/CommandInterface.cmi, IRP/src/Subsystems/PurchaseAP/Subsystems/Purchase/Purchase.mdo, features/Internal/_9000 FunctionalOptions/_9011GeneralFO.feature
=> #2291 #IRP-79 FO fixes

IRP/src/Configuration/CommandInterface.cmi, IRP/src/Configuration/Configuration.mdo
=> #2290 #IRP-78  Subsystem order

IRP/src/CommonModules/ControllerClientServer_V2/Module.bsl, IRP/src/CommonModules/ModelClientServer_V2/Module.bsl, IRP/src/CommonModules/ViewClient_V2/Module.bsl, IRP/src/Documents/RetailReturnReceipt/RetailReturnReceipt.mdo, IRP/src/Documents/RetailSalesReceipt/RetailSalesReceipt.mdo, features/Internal/_0050 Catalogs/_00504CompaniesCatalog.feature, features/Internal/_0260 Retail/_0260Retail.feature
=> #2316 #XMI-12 Filling Bank term in RSR RRR

IRP/src/Catalogs/CashAccounts/ObjectModule.bsl, IRP/src/Catalogs/Companies/ObjectModule.bsl, IRP/src/Catalogs/Items/ObjectModule.bsl, IRP/src/Catalogs/Partners/ObjectModule.bsl, IRP/src/Catalogs/Projects/ObjectModule.bsl, IRP/src/CommonModules/CheckDataPrivileged/Module.bsl, IRP/src/CommonModules/CommonFunctionsServer/Module.bsl, IRP/src/CommonModules/Localization/Module.bsl, features/External/Exportcatalog.feature, features/External/ProductSelectionFormPlusFilters.feature, features/Internal/_0050 Catalogs/_0101PartnersStructure.feature, features/Internal/_0910 Forms/_2000UserSettings.feature, features/Internal/_9600 AccessRightsSystem/_9600AccessRightsSystemDocuments.feature
=> #2318 #IRP-117 Unique Description

IRP/src/Configuration/Configuration.mdo, IRP/src/Constants/UseLegalNameContract/UseLegalNameContract.mdo, IRP/src/Documents/PurchaseInvoice/Forms/DocumentForm/Form.form, IRP/src/Documents/PurchaseReturn/Forms/DocumentForm/Form.form, IRP/src/Documents/SalesInvoice/Forms/DocumentForm/Form.form, IRP/src/Documents/SalesReportFromTradeAgent/Forms/DocumentForm/Form.form, IRP/src/Documents/SalesReportToConsignor/Forms/DocumentForm/Form.form, IRP/src/Documents/SalesReturn/Forms/DocumentForm/Form.form, IRP/src/FunctionalOptions/UseLegalNameContract/UseLegalNameContract.mdo, IRP/src/FunctionalOptions/UsePartnerTerms/UsePartnerTerms.mdo, IRP/src/Roles/BasicRole/Rights.rights, IRP/src/Roles/FullAccessOnlyRead/Rights.rights, features/Internal/_9600 AccessRightsSystem/_9603AccessRightsSystemRolesForDocuments.feature, features/Internal/_9910 Accounting/_9910AccountingSettings.feature
=> #2289 #IRP-77 Legal name contracts

IRP/src/CommonModules/DocVisitorCounterClient/Module.bsl, IRP/src/CommonModules/DocVisitorCounterServer/Module.bsl, IRP/src/Documents/RetailReturnReceipt/ObjectModule.bsl, IRP/src/Documents/RetailSalesReceipt/ObjectModule.bsl, IRP/src/Documents/VisitorCounter/Forms/ListForm/Form.form, features/Internal/_8510 FiscalPrinter/_8510FiscalPrinter.feature
#IRP-93 Description for document Visitors counter
#IRP-134 Prohibit cancel posting of RSR and RRR
=> #IRP-93 and #IRP-134

IRP/src/Catalogs/ItemTypes/ObjectModule.bsl, IRP/src/CommonModules/ControllerClientServer_V2/Module.bsl, IRP/src/CommonModules/FillingWithDefaultDataEvent/Module.bsl, IRP/src/Reports/R6021_BatchBalanceSimple/Templates/MainDataCompositionSchema/Template.dcs
#IRP-212 fixed report "R6021 Batch balance (simple)"  
#IRP-232 set default store when turn off FO "Use stores" 
#IRP-213 checking for empty attribute in ItemType
=> #IRP-212 #IRP-232 #IRP-213 "R6021 Batch balance (simple)", default store when turn off FO "Use stores", empty attribute in ItemType

IRP/src/Documents/SalesInvoice/ManagerModule.bsl
Если в SI заполнен Other period expense то движений по регистру Register  "R5021 Revenues" быть не должно.
=> ExpenseRevenueAccruals

IRP/src/Catalogs/Specifications/ManagerModule.bsl, features/Internal/_0050 Catalogs/_0051CreateItems.feature
https://bilistteam.atlassian.net/browse/IRP-330
=> #IRP-330 error when input text in InputField "specification" in ItemKey

IRP/src/Catalogs/AddAttributeAndPropertySets/ManagerModule.bsl, IRP/src/CommonModules/ExtensionServer/Module.bsl, IRP/src/CommonModules/UniqueID/Module.bsl, features/External/ImportData.feature, features/Internal/_0910 Forms/_1535AdditionalAttributes.feature
=> Now can add common attribute to attribute set. And unique can be any string
